// <auto-generated />
namespace Week06_OAuth.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class ModuleHasStudent : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ModuleHasStudent));
        
        string IMigrationMetadata.Id
        {
            get { return "201810182308302_ModuleHasStudent"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
